### ISSUE TITLE
각자의 스킬셋 공유!

### ISSUE THREAD

**Issue by yousunzoo** [KDT4-team6/KDT4-team6#1]
댓글로 자신은 어떤 라이브러리를 사용하는지를 공유해주세요!

**Comment by kjungit** [comment]
javascript, scss, html, figma, photoshop, illustrator

**Comment by yousunzoo** [comment]
- HTML, CSS, JS, SCSS
- 사용하는 번들러 : parcel
- 자주 사용하는 라이브러리 : GSAP, Swiper
- 그외 도구 : figma, photoshop, illustrator

**Comment by bongsee** [comment]
- [ ] HTML
- [ ] SCSS
- [ ] JavaScript
- [ ] Parcel

**Comment by FranzCho** [comment]
- html, css, scss, 
- javascript..

**Comment by KJDsports** [comment]
HTML
CSS
Javascript

**Comment by yousunzoo** [comment]
* 사용 언어 : HTML, SCSS, JS
* 사용 번들러 : parcel
* 기획 : 마켓컬리 디자인 + 농심몰 데이터
